development:
  adapter: postgresql
  encoding: utf8
  database: challenge_qcx_development
  pool: 3
  username: <%= ENV['DATABASE_POSTGRESQL_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_POSTGRESQL_PASSWORD'] %>
  host: <%= ENV['DATABASE_POSTGRESQL_HOST'] || 'localhost' %>

test:
  adapter: postgresql
  encoding: utf8
  database: challenge_qcx_test
  pool: 3
  username: <%= ENV['DATABASE_POSTGRESQL_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_POSTGRESQL_PASSWORD'] %>
  host: <%= ENV['DATABASE_POSTGRESQL_HOST'] || 'localhost' %>

# Add in future environments: qa, staging, production
